# DD2367 - Programing Assignment III: Quantum Arithmetics, QFT & Quantum walk #

Authors: Scott McHaffie, Jai Iyer, Venkatesh Elayaraja

In [33]:
# imports
import numpy as np
import matplotlib.pyplot as plt
from circleNotationClass import QubitSystem
from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from qiskit.quantum_info import Statevector


DTYPE = np.complex128

# **Task 1:** Quantum Arithmetics


This exercise aims to implement 3-qubit increment and decrement operators, =+ -=, using the IBM Qiskit framework and its Aer quantum computer simulator.

---

## **Task 1.1:** Increment and Decrement Operators

1. Prepare a superposition of quantum states using HAD QPU instructions. You can decide freely which superposition. This will determine the concurrent increment or decrement operator.

In [34]:
# Function to get statevector from Aer simulator
def statevector_from_aer(circ: QuantumCircuit) -> np.ndarray:
    backend = Aer.get_backend("aer_simulator_statevector")
    tqc = transpile(circ, backend)
    result = backend.run(tqc).result()
    return np.asarray(result.get_statevector(tqc), dtype=np.complex128)

# Initialise 3-qubit register
qc_id = QuantumCircuit(3, name="R")

# Create superposition  of |0> and |4> states
qc_id.h(2)


2. Plot the quantum states using the circle notation. 

In [35]:
# Please implement the circle notation visualization here
qc_id_state = np.sqrt(2) * Statevector(qc_id)
print (np.real(qc_id_state))

[1. 0. 0. 0. 1. 0. 0. 0.]


3. Perform an increment operation (by 1) +=

In [36]:
## INCREMENT CIRCUIT ##

# Step 1: Apply CCNOT | Control Qubits: 0, 1 | Target Qubit: 2
qc_id.ccx(0, 1, 2)

# Step 2: Apply CNOT | Control Qubits: 0 | Target Qubit: 1
qc_id.cx(0, 1)

# Step 3: Apply X gate | Target Qubit: 0
qc_id.x(0)

4. Plot the quantum states using the circle notation. 

In [37]:
# Please implement the circle notation visualization here
qc_id_state = np.sqrt(2) * Statevector(qc_id)
print (np.real(qc_id_state))

[0. 1. 0. 0. 0. 1. 0. 0.]


5. Perform a decrement operation (by 1) -=

In [38]:
## DECREMENT CIRCUIT ##

# Step 1: Apply X gate | Target Qubit: 0
qc_id.x(0)

# Step 2: Apply CNOT | Control Qubits: 0 | Target Qubit: 1
qc_id.cx(0, 1)


# Step 3: Apply CCNOT | Control Qubits: 0, 1 | Target Qubit: 2
qc_id.ccx(0, 1, 2)

6. Plot the quantum states using the circle notation. 

In [39]:
# Please implement the circle notation visualization here
qc_id_state = np.sqrt(2) * Statevector(qc_id)
print (np.real(qc_id_state))

[1. 0. 0. 0. 1. 0. 0. 0.]


## **Task 1.2** - Overflow & Underflow / Negative Numbers